flags: {}
packages:
 - hsbencher/
 - hsbencher-codespeed/
 - hsbencher-csv/
 - hsbencher-fusion/
 - hsbencher-graph/

# - hsbencher-analytics/

 # Not building examples for now:
 # - hsbencher/example/cabal/
 # - hsbencher/example/cabal/bench1/
 # - hsbencher/example/custom_tag/
 # - hsbencher/example/custom_tag/Bench/
 # - hsbencher/example/retries/
 # - hsbencher-codespeed/example/
 # - hsbencher-codespeed/example/Bench/
 # - hsbencher-fusion/examples/fusion_backend/
 # - hsbencher-fusion/examples/fusion_backend/Bench/
 # - hsbencher-fusion/examples/lowlevel_fusion/

 #- hsbencher-analytics/examples/fusion-analytics/
# - hsbencher-analytics/examples/fusion-analytics/Bench/

extra-deps: 
- handa-gdata-0.7.0.3
- simple-sql-parser-0.4.1

# Ugh, this prevents building in subdirs.  I.e. its not relative to stack.yaml location:
# See stack issue https://github.com/commercialhaskell/stack/issues/1340
# local-bin-path: ./bin/

system-ghc: false

# flags:
#  aeson:
#    old-locale: false

# [2015.12.23] Running into problems.  See DEVLOG
# resolver: lts-3.11
# resolver: lts-3.5
resolver: lts-5.16

allow-newer: true
