
flags: {}
packages:
 # The library that users depend on:
 - hsbencher/
 # (deprecated) Upload data to a codespeed instance:
 - hsbencher-codespeed/
 # Upload data to fusion tables:
 - hsbencher-fusion/
 # The latest attempt at direct graphing support for hsbencher data:
 - hsbencher-graph/
 # General utility:
 - cat-csv

 # Looks like we can throw this out:
 - old/hsbencher-csv/

 - location:
     git: https://github.com/bos/criterion
     commit: fa26f39a187f422adbb513ea459ee2700301f804
   extra-dep: true

# - hsbencher-analytics/

 # Not building examples for now:
 # - hsbencher/example/cabal/
 # - hsbencher/example/cabal/bench1/
 # - hsbencher/example/custom_tag/
 # - hsbencher/example/custom_tag/Bench/
 # - hsbencher/example/retries/
 # - hsbencher-codespeed/example/
 # - hsbencher-codespeed/example/Bench/
 # - hsbencher-fusion/examples/fusion_backend/
 # - hsbencher-fusion/examples/fusion_backend/Bench/
 # - hsbencher-fusion/examples/lowlevel_fusion/

 #- hsbencher-analytics/examples/fusion-analytics/
# - hsbencher-analytics/examples/fusion-analytics/Bench/

extra-deps:
- criterion-1.1.3.0
- handa-gdata-0.7.0.3
- simple-sql-parser-0.4.1

# Ugh, this prevents building in subdirs.  I.e. its not relative to stack.yaml location:
# See stack issue https://github.com/commercialhaskell/stack/issues/1340
local-bin-path: ./bin/

system-ghc: false

# flags:
#  aeson:
#    old-locale: false

# [2015.12.23] Running into problems.  See DEVLOG
# resolver: lts-3.11
# resolver: lts-3.5
resolver: lts-5.16

# allow-newer: true
