flags: {}
packages:
 - hsbencher/
 - hsbencher-codespeed/
 - hsbencher-csv/
 - hsbencher-fusion/

# - hsbencher-graph/
# - hsbencher-analytics/

 # Not building examples for now:
 # - hsbencher/example/cabal/
 # - hsbencher/example/cabal/bench1/
 # - hsbencher/example/custom_tag/
 # - hsbencher/example/custom_tag/Bench/
 # - hsbencher/example/retries/
 # - hsbencher-codespeed/example/
 # - hsbencher-codespeed/example/Bench/
 # - hsbencher-fusion/examples/fusion_backend/
 # - hsbencher-fusion/examples/fusion_backend/Bench/
 # - hsbencher-fusion/examples/lowlevel_fusion/

 #- hsbencher-analytics/examples/fusion-analytics/
# - hsbencher-analytics/examples/fusion-analytics/Bench/

extra-deps:
  - base-orphans-0.4.1
  - handa-gdata-0.7.0.3
  - io-streams-1.3.1.0
  # For handa-gdata.  I wish this could be avoided:
  - time-1.5.0.1
  - aeson-0.8.0.2
  - simple-sql-parser-0.4.1

flags:
  aeson:
    old-locale: false

resolver: lts-2.20
