

# TEMP: Fix the dependency on ntimes scripts:
all:
#	cp ../bench/ntimes_minmedmax . 
#	cp ../bench/ntimes . 
#	ghc ../bench/benchmark.hs -o benchmark.run
#	./benchmark.run
	hsbencher

clean:

distclean:
	rm -rf benchmark.run *.bak *.dat *.log ./bin/ ./build/ ./runs/
